### PR TITLE
Add classcontent command

### PR DESCRIPTION
**Pull request by mickaelandrieu**
This is a new command to help you list and check if a class content is correctly set.

Some captures from BackBee standard:

classcontent

list-contents

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @backbee/core-team

**Comment by fkroockmann** [comment]
You like create command ^^, so usefull thanks.
But can you check if the classcontent have a twig/phtml associeted else its not a available classcontent or put a flag.
You can check too if the template have a bbcontent helper (with raw) in the twig and add a flag in result of command. This point is number one of miss in dev.

**Comment by mickaelandrieu** [comment]
nice idea @fkroockmann I will take a look :)

**Comment by fkroockmann** [comment]
you can list available mod for the content (this function is in the renderer)

**Comment by mickaelandrieu** [comment]
@fkroockmann list the render modes is possible but not search for the associated file because the related method in Renderer is private.

**Comment by fkroockmann** [comment]
No, https://github.com/backbee/BackBee/blob/master/Renderer/Renderer.php#L470

**Comment by mickaelandrieu** [comment]
thank you for review @fkroockmann

**Pull request merged**
