### PR TITLE
[RFR] Added debug:event-listener

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Sorry for remotes, I will update this pull request soon.

This contribution introduce the new "debug:event-listener" command.

* ``debug:event-listener`` to list all registered listeners ordered by event

list events

* ``debug:event-listener <eventName>`` to list all registered listeners for an event

listeners-for-event

### CODE REVIEW

**Comment by fkroockmann** [comment]
you can replace the service's tag (@cache.listener) ?

**Comment by mickaelandrieu** [comment]
@fkroockmann not for now, but if you want to improve this command I agree to add a way to replace service ids by their class

**Comment by fkroockmann** [comment]
yes thanks :)

**Comment by mickaelandrieu** [comment]
thanks for review

**Pull request merged**
